In [153]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("shriyashjagtap/e-commerce-customer-for-behavior-analysis")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\Imali Shehara\.cache\kagglehub\datasets\shriyashjagtap\e-commerce-customer-for-behavior-analysis\versions\4

In [154]:
import os
print(os.listdir(path))

['ecommerce_customer_data_custom_ratios.csv', 'ecommerce_customer_data_large.csv']

In [155]:
import pandas as pd
import os

path = r"C:\Users\Imali Shehara\.cache\kagglehub\datasets\shriyashjagtap\e-commerce-customer-for-behavior-analysis\versions\4"
file_name = 'ecommerce_customer_data_custom_ratios.csv'

data = pd.read_csv(os.path.join(path, file_name))

# Quick look
print(data.shape)
print(data.head())
print(data.info())

(250000, 13)
   Customer ID        Purchase Date Product Category  Product Price  Quantity  \
0        46251  2020-09-08 09:38:32      Electronics             12         3
1        46251  2022-03-05 12:56:35             Home            468         4
2        46251  2022-05-23 18:18:01             Home            288         2
3        46251  2020-11-12 13:13:29         Clothing            196         1
4        13593  2020-11-27 17:55:11             Home            449         1

   Total Purchase Amount Payment Method  Customer Age  Returns  \
0                    740    Credit Card            37      0.0
1                   2739         PayPal            37      0.0
2                   3196         PayPal            37      0.0
3                   3509         PayPal            37      0.0
4                   3452    Credit Card            49      0.0

         Customer Name  Age  Gender  Churn
0  Christine Hernandez   37    Male      0
1  Christine Hernandez   37    Male      0
2  Christine Hernandez   37    Male      0
3  Christine Hernandez   37    Male      0
4          James Grant   49  Female      1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Customer ID            250000 non-null  int64
 1   Purchase Date          250000 non-null  object
 2   Product Category       250000 non-null  object
 3   Product Price          250000 non-null  int64
 4   Quantity               250000 non-null  int64
 5   Total Purchase Amount  250000 non-null  int64
 6   Payment Method         250000 non-null  object
 7   Customer Age           250000 non-null  int64
 8   Returns                202404 non-null  float64
 9   Customer Name          250000 non-null  object
 10  Age                    250000 non-null  int64
 11  Gender                 250000 non-null  object
 12  Churn                  250000 non-null  int64
dtypes: float64(1), int64(7), object(5)
memory usage: 24.8+ MB
None

In [156]:
data.isna().sum()

Customer ID                  0
Purchase Date                0
Product Category             0
Product Price                0
Quantity                     0
Total Purchase Amount        0
Payment Method               0
Customer Age                 0
Returns                  47596
Customer Name                0
Age                          0
Gender                       0
Churn                        0
dtype: int64

In [157]:
# Check for duplicates
print("Number of duplicate rows:", data.duplicated().sum())

Number of duplicate rows: 0

In [158]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Customer ID            250000 non-null  int64
 1   Purchase Date          250000 non-null  object
 2   Product Category       250000 non-null  object
 3   Product Price          250000 non-null  int64
 4   Quantity               250000 non-null  int64
 5   Total Purchase Amount  250000 non-null  int64
 6   Payment Method         250000 non-null  object
 7   Customer Age           250000 non-null  int64
 8   Returns                202404 non-null  float64
 9   Customer Name          250000 non-null  object
 10  Age                    250000 non-null  int64
 11  Gender                 250000 non-null  object
 12  Churn                  250000 non-null  int64
dtypes: float64(1), int64(7), object(5)
memory usage: 24.8+ MB

In [159]:
data

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Total Purchase Amount,Payment Method,Customer Age,Returns,Customer Name,Age,Gender,Churn
0,46251,2020-09-08 09:38:32,Electronics,12,3,740,Credit Card,37,0.0,Christine Hernandez,37,Male,0
1,46251,2022-03-05 12:56:35,Home,468,4,2739,PayPal,37,0.0,Christine Hernandez,37,Male,0
2,46251,2022-05-23 18:18:01,Home,288,2,3196,PayPal,37,0.0,Christine Hernandez,37,Male,0
3,46251,2020-11-12 13:13:29,Clothing,196,1,3509,PayPal,37,0.0,Christine Hernandez,37,Male,0
4,13593,2020-11-27 17:55:11,Home,449,1,3452,Credit Card,49,0.0,James Grant,49,Female,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,33308,2023-08-10 13:39:06,Clothing,279,2,2187,PayPal,55,1.0,Michelle Flores,55,Male,1
249996,48835,2021-11-23 01:30:42,Home,27,1,3615,Credit Card,42,1.0,Jeremy Rush,42,Female,1
249997,21019,2020-07-02 14:04:48,Home,17,5,2466,Cash,41,0.0,Tina Craig,41,Male,0
249998,49234,2020-12-30 02:02:40,Books,398,2,3668,Crypto,34,0.0,Jennifer Cooper,34,Female,1
249999,16971,2021-03-13 16:28:35,Electronics,425,4,2370,Cash,36,1.0,Justin Lawson,36,Female,1

In [160]:
data['Returns'] = data['Returns'].fillna(0)

In [161]:
data.isna().sum()

Customer ID              0
Purchase Date            0
Product Category         0
Product Price            0
Quantity                 0
Total Purchase Amount    0
Payment Method           0
Customer Age             0
Returns                  0
Customer Name            0
Age                      0
Gender                   0
Churn                    0
dtype: int64

In [162]:
data = data.drop(columns=['Customer Name', 'Customer ID', 'Purchase Date', 'Customer Age'])

In [163]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 9 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Product Category       250000 non-null  object
 1   Product Price          250000 non-null  int64
 2   Quantity               250000 non-null  int64
 3   Total Purchase Amount  250000 non-null  int64
 4   Payment Method         250000 non-null  object
 5   Returns                250000 non-null  float64
 6   Age                    250000 non-null  int64
 7   Gender                 250000 non-null  object
 8   Churn                  250000 non-null  int64
dtypes: float64(1), int64(5), object(3)
memory usage: 17.2+ MB

In [164]:
from sklearn.preprocessing import LabelEncoder
import joblib

# Create separate LabelEncoders
le_category = LabelEncoder()
le_payment = LabelEncoder()
le_gender = LabelEncoder()

# Fit and transform
data['Product Category'] = le_category.fit_transform(data['Product Category'])
data['Payment Method'] = le_payment.fit_transform(data['Payment Method'])
data['Gender'] = le_gender.fit_transform(data['Gender'])

# Save LabelEncoders
joblib.dump(le_category, "le_category.pkl")
joblib.dump(le_payment, "le_payment.pkl")
joblib.dump(le_gender, "le_gender.pkl")

['le_gender.pkl']

In [165]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 9 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Product Category       250000 non-null  int64
 1   Product Price          250000 non-null  int64
 2   Quantity               250000 non-null  int64
 3   Total Purchase Amount  250000 non-null  int64
 4   Payment Method         250000 non-null  int64
 5   Returns                250000 non-null  float64
 6   Age                    250000 non-null  int64
 7   Gender                 250000 non-null  int64
 8   Churn                  250000 non-null  int64
dtypes: float64(1), int64(8)
memory usage: 17.2 MB

In [166]:
data

,Product Category,Product Price,Quantity,Total Purchase Amount,Payment Method,Returns,Age,Gender,Churn
0,2,12,3,740,1,0.0,37,1,0
1,3,468,4,2739,3,0.0,37,1,0
2,3,288,2,3196,3,0.0,37,1,0
3,1,196,1,3509,3,0.0,37,1,0
4,3,449,1,3452,1,0.0,49,0,1
...,...,...,...,...,...,...,...,...,...
249995,1,279,2,2187,3,1.0,55,1,1
249996,3,27,1,3615,1,1.0,42,0,1
249997,3,17,5,2466,0,0.0,41,1,0
249998,0,398,2,3668,2,0.0,34,0,1
249999,2,425,4,2370,0,1.0,36,0,1

In [167]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
features_to_scale = ['Total Purchase Amount', 'Quantity', 'Returns', 'Age', 'Product Price']
data[features_to_scale] = scaler.fit_transform(data[features_to_scale])

# Save scaler
joblib.dump(scaler, "scaler.pkl")

['scaler.pkl']

In [ ]:
from sklearn.cluster import KMeans


X_for_cluster = data[['Product Price','Quantity','Total Purchase Amount','Returns']]
kmeans = KMeans(n_clusters=4, random_state=42)
data['Cluster'] = kmeans.fit_predict(X_for_cluster)


joblib.dump(kmeans, "customer_segment_model.pkl")

cluster_summary = data.groupby('Cluster').mean()
print(cluster_summary[['Product Price','Quantity','Total Purchase Amount','Returns']])

         Product Price  Quantity  Total Purchase Amount   Returns
Cluster
0             0.865585  0.001359              -0.022582  1.216931
1             0.006860 -0.003145               0.867550 -0.821739
2            -0.001564  0.000629              -0.866270 -0.821739
3            -0.863994  0.002357               0.022796  1.216931

In [ ]:
from imblearn.over_sampling import SMOTE

X = data.drop(['Churn'], axis=1)
y = data['Churn']

# Balance classes using SMOTE
smote = SMOTE(random_state=42)
X_balanced, y_balanced = smote.fit_resample(X, y)


print(pd.Series(y_balanced).value_counts())

Churn
0    200126
1    200126
Name: count, dtype: int64

In [170]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_balanced, y_balanced, test_size=0.2, random_state=42
)

In [171]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Save model
joblib.dump(model, "churn_rf_model.pkl")

['churn_rf_model.pkl']

In [172]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:,1]

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))

Accuracy: 0.7989031992105033
              precision    recall  f1-score   support

           0       0.79      0.81      0.80     40207
           1       0.81      0.79      0.80     39844

    accuracy                           0.80     80051
   macro avg       0.80      0.80      0.80     80051
weighted avg       0.80      0.80      0.80     80051

Confusion Matrix:
 [[32644  7563]
 [ 8535 31309]]
ROC-AUC: 0.8755275686226599